name: bacterial_variant_pipeline
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - fastqc
  - fastp
  - bwa
  - samtools
  - freebayes
  - bcftools
  - snpeff
  - multiqc
  - streamlit
  - pandas